import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import stylesCard from '../styles/Card.module.css'
import Images from '../API/music';

import Card from '../components/Card'
import DiskCard from '../components/DiskCard'

// export async function getStaticProps() {
//   const db = await myDB.connect({
//     host: process.env.DB_HOST,
//     username: process.env.DB_USER,
//     password: process.env.DB_PASS,
//   })
// }

export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className="h-full h-screen min-h-screen w-full flex">
          <div className="container w-2/12 h-full min-h-screen">
            <div className="min-w-30 h-full">
              <div className="container flex flex-col justify-start pt-10 h-1/6">
                <div className="text-xs shadow flex justify-center">
                  <input className="max-w-md border-b bg-transparent text-white mr-4 outline-none truncate ..." type="text" placeholder="Try 'Kendrick Lamar'" />
                  <button className="bg-indigo-700 hover:bg-indigo-600 rounded outline-none text-white p-2 pl-4 pr-4">
                    <p className="font-semibold">Search</p>
                  </button>
                </div>
              </div>
              <div className="container flex flex-col justify-start h-4/6  border-r">
                <nav>
                  <ul className="text-white font-light flex-col px-6">
                    <span className={`${styles.spanSelected}`}></span>
                    <li className="flex pb-2">
                      <Link href="/">
                        <a className="flex ml-4">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-4 mr-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
                          </svg>
                          Home
                        </a>
                      </Link>
                    </li>
                    <li className="flex pb-2">
                      <Link href="/">
                        <a className="flex ml-4">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-4 mr-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
                          </svg>
                          Recommendations
                        </a></Link>
                    </li>
                    <li className="flex pb-2">
                      <Link href="/">
                        <a className="flex ml-4">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-4 mr-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
                          </svg>
                          Top songs
                        </a></Link>
                    </li>
                    <li className="flex pb-2">
                      <Link href="/">
                        <a className="flex ml-4">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-4 mr-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19V6l12-3v13M9 19c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zm12-3c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zM9 10l12-3" />
                          </svg>
                          Recently heard
                        </a></Link>
                    </li>
                  </ul>
                </nav>
              </div>
              <div className="container flex justify-center h-1/6">
                <div className="flex w-full items-center justify-center">
                  <div className="flex w-11/12 h-16 rounded bg-white bg-opacity-5 text-gray-300 justify-between px-4 items-center">
                    <div className="flex items-center w-full">
                      <div className="song flex items-center w-3/6">
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 mr-2 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19V6l12-3v13M9 19c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zm12-3c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3" />
                        </svg>
                        <p className="font-light text-xs truncate ... ">You Gon` Learn(feat. Royce Da 5`9" & White Gold)</p>
                      </div>
                      <div className="flex w-3/6">
                        <div className="left flex items-center">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
                            <path fillRule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clipRule="evenodd" />
                          </svg>
                        </div>
                        <div className="play flex items-center">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" />
                          </svg>
                        </div>
                        <div className="stop flex items-center">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 10a1 1 0 011-1h4a1 1 0 011 1v4a1 1 0 01-1 1h-4a1 1 0 01-1-1v-4z" />
                          </svg>
                        </div>
                        <div className="right flex items-center">
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
                            <path fillRule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clipRule="evenodd" />
                          </svg>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="container w-10/12 h-3/6">
            <div className="w-full bg-red-500">
            </div>
            <div className="container space-y-8 pl-4">
              <div className="w-full relative overflow-hidden">
                <div className="container text-white top-10 absolute font-light text-2xl mb-2">
                  <h1>Featured</h1>
                </div>
                <div className={`${stylesCard.scroll} pt-24 pb-4 flex space-x-8 overflow-y-hidden overflow-x-scroll`}>
                  {Object.keys(Images).map(card => (
                    <Card
                      key={card}
                      colorBg={Images[card].albums.colorBg}
                      imageURL={Images[card].principal.imageURL}
                      albumName={Images[card].albums.albumName}
                      authorName={Images[card].principal.authorName}
                    />
                  ))
                  }
                </div>
              </div>
              <div className="w-full overflow-hidden h-2/6">
                <div className="container text-white font-light text-2xl mb-2">
                  <h1>Popular</h1>
                </div>
                <div className={`${stylesCard.scroll} pt-4 pb-4 flex space-x-8 overflow-x-scroll`}>
                  {Object.keys(Images).map(card => (
                    <DiskCard
                      key={card}
                      imageURL={Images[card].albums.imageURL}
                      albumName={Images[card].albums.albumName}
                      authorName={Images[card].principal.authorName}
                    />
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
